### ISSUE TITLE
Problems adding links

### ISSUE THREAD

**Issue by ralphtheninja** [ptahproject/examples#11]
When I add a link I get the following errors in the console:

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 215, in write
    self._write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
## error: [Errno 104] Connection reset by peer

Exception happened during processing of request from ('127.0.0.1', 33776)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 641, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

It happens exactly after I click the "Add"-button on the page where you add new links.

**Comment by ralphtheninja** [comment]
I also have the same kind of errors when trying to add a new user in ptah_crowd. Not sure if this is even related to ptah or if it's something else.

**Comment by mcdonc** [comment]
Other than the console message, is there a problem with the functionality?  E.g. does the link not get added?

**Comment by ralphtheninja** [comment]
The link gets added.

2012/1/11 Chris McDonough <
reply@reply.github.com

**Comment by ralphtheninja** [comment]
When I go to the login.html page I get this error from ptah

2012-01-11 02:20:23,677 WARNI [ptah][MainThread] Can't find layout 'ptah-page' for context '<pyramid.traversal.DefaultRootFactory instance at 0xa019dec>'

**Comment by mcdonc** [comment]
The original issue is caused by code in wsgiref (the WSGI server) that emits a traceback when the browser disconnects unexpectedly from the server.  It's not really an error, it's just annoying.  These messages will disappear (or at least appear differently) if you start to use a different WSGI server.

The second issue I'd make into its own issue, it's unlreated to your original.

**Comment by ralphtheninja** [comment]
Roger roger. New issue coming up. Thanks. Guess I'm adding it to ptah_crowd then, or?
