### ISSUE TITLE
Need to add "var" directory manually to run ptah_minicms scarfold

### ISSUE THREAD

**Issue by bismigalis** [ptahproject/examples#3]
When trying ptah_minicms scarfold, after this command bin/pserve development.ini 
I have error :
/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/ext/declarative.py:1259: SAWarning: The classname 'ApplicationRoot' is already in the registry of this declarative base, mapped to <class 'ptah.cms.root.ApplicationRoot'>
  _as_declarative(cls, classname, cls.__dict__)
Traceback (most recent call last):
  File "../../bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.3a2', 'console_scripts', 'pserve')()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/scripts/pserve.py", line 31, in main
    command.run()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/scripts/pserve.py", line 274, in run
    relative_to=base, global_conf=vars)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/scripts/pserve.py", line 302, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, *_kw)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, *_kw)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, *_context.local_conf)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/util.py", line 56, in fix_call
    val = callable(_args, *_kw)
  File "/home/ruslan/workspace/venv/examples/ptah_minicms/ptah_minicms/app.py", line 61, in main
    Base.metadata.create_all()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/schema.py", line 2434, in create_all
    tables=tables)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/engine/base.py", line 2224, in _run_visitor
    conn = self.contextual_connect(close_with_result=False)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/engine/base.py", line 2334, in contextual_connect
    self.pool.connect(), 
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 210, in connect
    return _ConnectionFairy(self).checkout()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 371, in __init__
    rec = self._connection_record = pool._do_get()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 758, in _do_get
    return self._create_connection()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 174, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 256, in __init__
    self.connection = self.__connect()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 316, in __connect
    connection = self.__pool._creator()
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(_cargs, *_cparams)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-i686.egg/sqlalchemy/engine/default.py", line 280, in connect
    return self.dbapi.connect(_cargs, **cparams)
sqlalchemy.exc.OperationalError: (OperationalError) unable to open database file None None

**Comment by fafhrd91** [comment]
fixed
