### ISSUE TITLE
In ptah_minicms when trying to add Folder or Page exeption emits

### ISSUE THREAD

**Issue by bismigalis** [ptahproject/examples#4]
In ptah_minicms when trying to add Folder or Page exeption emits:

Traceback (most recent call last):
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid_debugtoolbar-0.9.4-py2.7.egg/pyramid_debugtoolbar/panels/performance.py", line 55, in resource_timer_handler
    result = handler(request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid_tm-0.3-py2.7.egg/pyramid_tm/**init**.py", line 61, in tm_tween
    response = handler(request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/config/views.py", line 149, in _owrapped_view
    response = view(context, request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/config/views.py", line 335, in rendered_view
    context)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/renderers.py", line 395, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/renderers.py", line 424, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/renderers.py", line 420, in render
    result = renderer(value, system_values)
  File "/home/ruslan/workspace/venv/lib/python2.7/site-packages/pyramid-1.3a2-py2.7.egg/pyramid/chameleon_zpt.py", line 50, in __call__
    raise ValueError('renderer was passed non-dictionary as value')
ValueError: renderer was passed non-dictionary as value

**Comment by fafhrd91** [comment]
this bug is fixed.
